---
  env:
    TEST_IMAGE=certbot-configurator-tests

  services:
    - docker

  before_install:
    - docker build -t ${TEST_IMAGE} -f tests/Dockerfile.tests .

  script:
    - docker run --rm -v $(pwd):/certbot-configurator ${TEST_IMAGE} /certbot-configurator/tests/run.sh
