---
  env:
    TEST_IMAGE=certbot-configurator-tests
    DOMAIN_NAME=test.local

  services:
    - docker

  before_install:
    - docker build -t ${TEST_IMAGE} -f tests/Dockerfile.tests .

  script:
    # YAML multiline value example
    - |
        docker run --rm -v $(pwd):/certbot-configurator \
            --privileged \
            -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
            -w /certbot-configurator/tests \
            -e DOMAIN_NAME=${DOMAIN_NAME} \
            --add-host ${DOMAIN_NAME}:172.17.0.1 \
            ${TEST_IMAGE} \
            bash_unit tests.sh

  after_script:
    - docker rmi ${TEST_IMAGE}
