FROM ubuntu:xenial

ENV UNPRIVILEGED_USER=user \
    TERM=xterm

RUN apt-get update && \
    apt-get install -y \
        sudo && \
    apt-get clean && \
    adduser --disabled-password --quiet --disabled-login --gecos "" ${UNPRIVILEGED_USER} && \

USER ${UNPRIVILEGED_USER}
