FROM ubuntu:xenial

ENV SHUNIT_SOURCE_FOLDER=/shunit \
    UNPRIVILEGED_USER=user \
    TERM=xterm \
    SHUNIT_COMMAND=shunit2

RUN apt-get update && \
    apt-get install -y \
        git \
        sudo && \
    apt-get clean && \
    adduser --disabled-password --quiet --disabled-login --gecos "" ${UNPRIVILEGED_USER} && \
    mkdir -p ${SHUNIT_SOURCE_FOLDER} && \
    git clone https://github.com/kward/shunit2.git ${SHUNIT_SOURCE_FOLDER} && \
    ln -s ${SHUNIT_SOURCE_FOLDER}/shunit2 /usr/sbin/${SHUNIT_COMMAND}

USER ${UNPRIVILEGED_USER}
