FROM ubuntu:xenial

LABEL maintainer="devops@onix-systems.com"

ENV USER=user \
    TERM=xterm \
    SOURCE_FOLDER=/source

RUN apt-get update && \
    apt-get install -y \
        git \
        sudo && \
    apt-get clean && \
    mkdir -p ${SOURCE_FOLDER} && \
    git clone https://github.com/pgrange/bash_unit.git ${SOURCE_FOLDER} && \
    ln -s ${SOURCE_FOLDER}/bash_unit /usr/sbin/bash_unit && \
    adduser --disabled-password --quiet --disabled-login --gecos "" ${USER} && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER}

USER ${USER}
